# Generated by Django 4.0.4 on 2022-05-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('cur', models.IntegerField()),
                ('measure', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=10)),
                ('normofconsumption', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='animal',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Accountings.meal'),
        ),
    ]
